const WCO = { id: "wco", name: "World Customs Organization", url: "https://www.wcoomd.org/", capabilities: ["hs", "classification", "origin", "valuation", "customs"] };
const JURISDICTIONS = [
  ["PK","Pakistan","Pakistan Customs / FBR","https://www.fbr.gov.pk/categ/customs-tariff/144",8],
  ["AE","United Arab Emirates","Federal Customs Authority","https://www.fca.gov.ae/",8],["SA","Saudi Arabia","ZATCA","https://zatca.gov.sa/",12],["QA","Qatar","General Authority of Customs","https://www.customs.gov.qa/",8],["KW","Kuwait","Kuwait General Administration of Customs","https://www.customs.gov.kw/",8],["BH","Bahrain","Bahrain Customs Affairs","https://www.customs.gov.bh/",8],["OM","Oman","Royal Oman Police Customs","https://www.customs.gov.om/",8],
  ["US","United States","U.S. Customs and Border Protection","https://www.cbp.gov/",10],["GB","United Kingdom","HM Revenue & Customs","https://www.gov.uk/government/organisations/hm-revenue-customs",10],["CA","Canada","Canada Border Services Agency","https://www.cbsa-asfc.gc.ca/",10],["AU","Australia","Australian Border Force","https://www.abf.gov.au/",10],["NZ","New Zealand","New Zealand Customs Service","https://www.customs.govt.nz/",10],
  ["DE","Germany","German Customs","https://www.zoll.de/",10],["FR","France","French Customs","https://www.douane.gouv.fr/",10],["IT","Italy","Italian Customs and Monopolies Agency","https://www.adm.gov.it/",10],["ES","Spain","Agencia Tributaria Customs","https://sede.agenciatributaria.gob.es/",10],["NL","Netherlands","Dutch Customs","https://www.douane.nl/",10],["BE","Belgium","Belgian Customs","https://finance.belgium.be/",10],["CH","Switzerland","Federal Office for Customs and Border Security","https://www.bazg.admin.ch/",10],["AT","Austria","Austrian Customs","https://www.bmf.gv.at/",10],["SE","Sweden","Swedish Customs","https://www.tullverket.se/",10],["NO","Norway","Norwegian Customs","https://www.toll.no/",10],["DK","Denmark","Danish Customs","https://skat.dk/",10],["FI","Finland","Finnish Customs","https://www.tulli.fi/",10],["IE","Ireland","Irish Revenue Customs","https://www.revenue.ie/",10],["JP","Japan","Japan Customs","https://www.customs.go.jp/",10],["KR","South Korea","Korea Customs Service","https://www.customs.go.kr/",10],["SG","Singapore","Singapore Customs","https://www.customs.gov.sg/",10],["HK","Hong Kong","Hong Kong Customs and Excise","https://www.customs.gov.hk/",10],["TW","Taiwan","Taiwan Customs","https://web.customs.gov.tw/",10],["IL","Israel","Israel Tax Authority Customs","https://www.gov.il/en/departments/israel_tax_authority",10],["LU","Luxembourg","Luxembourg Customs","https://douanes.public.lu/",10],["IS","Iceland","Icelandic Customs","https://www.skatturinn.is/",10],
  ["IN","India","Central Board of Indirect Taxes and Customs","https://www.cbic.gov.in/",8],["CN","China","General Administration of Customs of China","https://www.customs.gov.cn/",8],["MY","Malaysia","Royal Malaysian Customs Department","https://www.customs.gov.my/",8],["TH","Thailand","Thai Customs Department","https://www.customs.go.th/",8],["ID","Indonesia","Directorate General of Customs and Excise","https://www.beacukai.go.id/",8],["VN","Vietnam","Vietnam Customs","https://www.customs.gov.vn/",8],["TR","Türkiye","Ministry of Trade Customs","https://www.trade.gov.tr/",8],["BR","Brazil","Receita Federal","https://www.gov.br/receitafederal/",8],["MX","Mexico","ANAM / SAT Customs","https://www.gob.mx/anam",8],["ZA","South Africa","South African Revenue Service Customs","https://www.sars.gov.za/",8]
];
const FEATURES = ["HS classification","national tariff code mapping","customs duty","VAT/GST/import taxes","tariff preferences","rules of origin","customs valuation","anti-dumping/countervailing","prohibited and restricted goods","import/export permits","quotas and licensing","sanctions and export controls","free-trade agreements","binding/ruling research","customs declarations","trade documentation","landed-cost calculation","trade compliance audit"];
export function listCustomsJurisdictions(){ return JURISDICTIONS.map(([code,country,authority,url,digits])=>({code,country,authority,url,national_code_digits:digits,features:FEATURES})); }
export function searchCustoms(query="", jurisdiction=""){ const q=(String(query)+" "+String(jurisdiction)).toLowerCase(); return listCustomsJurisdictions().filter(x=>q.includes(x.country.toLowerCase())||q.includes(x.code.toLowerCase())||q.includes("custom")||q.includes("hs")||q.includes("tariff")); }
export function buildHsResearchPlan({product="",origin="",destination="",jurisdiction=""}={}){ return {product,origin,destination,jurisdiction,required_fields:["commercial description","composition/material","function/use","form/condition","brand/model where relevant","technical specifications","packaging","country of origin"],verification:[WCO,...listCustomsJurisdictions().filter(x=>x.country.toLowerCase()===String(jurisdiction).toLowerCase())],checks:["HS heading/subheading","national tariff extension","duty/tax rates","origin/preference","valuation","restrictions/permits","trade remedies","sanctions/export controls"],warning:"HS classification and tariff treatment are jurisdiction- and fact-specific; UZMO must verify current official customs sources before treating a code or rate as final."}; }
export { WCO };
