/* ABZEMO AI Search — separate from the ABZEMO AI visitor bot */
(function(){
"use strict";
const SUPPORTED_LANGUAGES=["English","Arabic","Urdu","Roman Urdu","French","Italian","Spanish","German","Portuguese","Dutch","Turkish","Persian","Hindi","Bengali","Punjabi","Sindhi","Pashto","Malay","Indonesian","Chinese","Japanese","Korean","Vietnamese","Thai","Tamil","Telugu","Marathi","Gujarati","Kannada","Malayalam","Nepali","Russian","Ukrainian","Polish","Czech","Slovak","Hungarian","Romanian","Bulgarian","Greek","Hebrew","Swedish","Norwegian","Danish","Finnish","Icelandic","Swahili","Somali","Amharic","Zulu","Afrikaans","Filipino","Persian (Dari)"];
const pageLinks=[["Home","index.html"],["About ABZEMO","about.html"],["Mission","mission.html"],["Vision","vision.html"],["Director's Note","director-note.html"],["Solutions","solutions.html"],["Industries","industries.html"],["ABZEMO AI","abzemo-ai.html"],["Ventures","ventures.html"],["Contact","contact.html"],["Privacy Policy","privacy.html"],["Terms & Conditions","terms.html"]];
function icon(name){const p={search:'<circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path>',mic:'<rect x="8" y="3" width="8" height="12" rx="4"></rect><path d="M5 11a7 7 0 0 0 14 0M12 18v3M9 21h6"></path>',arrow:'<path d="M4 12h15"></path><path d="m13 6 6 6-6 6"></path>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+p[name]+'</svg>'}
function normalize(v){return String(v||"").toLowerCase().replace(/\s+/g," ").trim()}
function localSearch(q){q=normalize(q);if(!q)return[];return pageLinks.map(x=>{const t=normalize(x[0]),score=t===q?100:(t.includes(q)?70:(q.split(" ").some(w=>w.length>2&&t.includes(w))?35:0));return{title:x[0],url:x[1],score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,6)}
function detectLanguage(){return(navigator.language||"en").toLowerCase()}
function init(){
 if(document.querySelector(".abzemo-search-trigger"))return;
 const navbar=document.querySelector(".navbar");if(!navbar)return;
 const build=function(){
  if(document.querySelector(".abzemo-search-trigger"))return;
  const trigger=document.createElement("button");trigger.className="abzemo-search-trigger";trigger.type="button";trigger.setAttribute("aria-label","Open ABZEMO AI Search");trigger.setAttribute("aria-controls","abzemoSearchPanel");trigger.setAttribute("aria-expanded","false");trigger.innerHTML=icon("search");navbar.style.position="relative";navbar.appendChild(trigger);
 const backdrop=document.createElement("div");backdrop.className="abzemo-search-backdrop";
 const panel=document.createElement("section");panel.className="abzemo-search-panel";panel.id="abzemoSearchPanel";panel.setAttribute("aria-label","ABZEMO AI Search");panel.innerHTML='<div class="abzemo-search-inner"><div class="abzemo-search-top"><div class="abzemo-search-kicker">Search with ABZEMO AI</div><button class="abzemo-search-close" type="button" aria-label="Close search">×</button></div><form class="abzemo-search-box"><input class="abzemo-search-input" autocomplete="off" placeholder="Search ABZEMO with natural language…" aria-label="Search ABZEMO"><button class="abzemo-search-icon-btn" type="button" aria-label="Search by voice" title="Voice search">'+icon("mic")+'</button><button class="abzemo-search-submit" type="submit" aria-label="Search">'+icon("arrow")+'</button></form><div class="abzemo-search-hints"><button class="abzemo-search-hint" type="button">What does ABZEMO build?</button><button class="abzemo-search-hint" type="button">Explore ABZEMO AI</button><button class="abzemo-search-hint" type="button">What industries do we serve?</button></div><div class="abzemo-search-status"></div><div class="abzemo-search-results"></div><div class="abzemo-search-footnote">AI Search is separate from the ABZEMO AI visitor assistant. Supports 50+ language experiences.</div></div>';
 document.body.appendChild(backdrop);document.body.appendChild(panel);
 const input=panel.querySelector(".abzemo-search-input"),form=panel.querySelector(".abzemo-search-box"),status=panel.querySelector(".abzemo-search-status"),results=panel.querySelector(".abzemo-search-results"),close=panel.querySelector(".abzemo-search-close"),mic=panel.querySelector(".abzemo-search-icon-btn");
 function open(){backdrop.classList.add("active");panel.classList.add("active");trigger.setAttribute("aria-expanded","true");document.body.style.overflow="hidden";setTimeout(()=>input.focus(),80)}
 function shut(){backdrop.classList.remove("active");panel.classList.remove("active");trigger.setAttribute("aria-expanded","false");document.body.style.overflow=""}
 function renderLocal(items){results.innerHTML="";items.forEach(item=>{const a=document.createElement("a");a.className="abzemo-search-result";a.href=item.url;a.innerHTML='<span class="abzemo-search-result-title"></span><span class="abzemo-search-result-url"></span><span class="abzemo-search-result-snippet">Open this ABZEMO section.</span>';a.querySelector(".abzemo-search-result-title").textContent=item.title;a.querySelector(".abzemo-search-result-url").textContent=item.url;results.appendChild(a)})}
 async function submit(query){query=String(query||"").trim();if(!query)return;status.textContent="Understanding your request…";results.innerHTML="";try{const response=await fetch("/api/ai-search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,language:detectLanguage(),supported_languages:SUPPORTED_LANGUAGES,source:window.location.href})});if(!response.ok)throw new Error("AI search endpoint unavailable");const data=await response.json();if(data.answer){const answer=document.createElement("div");answer.className="abzemo-search-answer";const strong=document.createElement("strong");strong.textContent="AI Search";answer.appendChild(strong);answer.appendChild(document.createTextNode(" — "+data.answer));results.appendChild(answer)}if(Array.isArray(data.results))data.results.slice(0,8).forEach(item=>{if(!item||!item.url)return;const a=document.createElement("a");a.className="abzemo-search-result";a.href=item.url;a.innerHTML='<span class="abzemo-search-result-title"></span><span class="abzemo-search-result-url"></span><span class="abzemo-search-result-snippet"></span>';a.querySelector(".abzemo-search-result-title").textContent=item.title||"ABZEMO result";a.querySelector(".abzemo-search-result-url").textContent=item.url;a.querySelector(".abzemo-search-result-snippet").textContent=item.snippet||"";results.appendChild(a)});status.textContent="Results ready."}catch(error){const local=localSearch(query);status.textContent=local.length?"AI Search is not connected yet — showing direct ABZEMO matches.":"No direct ABZEMO match found.";renderLocal(local)}}
 trigger.addEventListener("click",open);close.addEventListener("click",shut);backdrop.addEventListener("click",shut);form.addEventListener("submit",e=>{e.preventDefault();submit(input.value)});panel.querySelectorAll(".abzemo-search-hint").forEach(btn=>btn.addEventListener("click",()=>{input.value=btn.textContent;submit(input.value)}));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&panel.classList.contains("active"))shut()});
 const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){mic.disabled=true;mic.title="Voice search is not supported by this browser"}else{const recognition=new SR();recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;mic.addEventListener("click",()=>{recognition.lang=detectLanguage();try{recognition.start();status.textContent="Listening…"}catch(e){}});recognition.onresult=e=>{input.value=(e.results[0][0].transcript||"").trim();status.textContent="Voice captured — searching…";submit(input.value)};recognition.onerror=()=>{status.textContent="Microphone permission is required or voice input failed."}}
 };
 const style=document.querySelector('link[data-abzemo-search-style]')||document.createElement("link");
 if(!style.parentNode){style.rel="stylesheet";style.href="abzemo-search.css";style.setAttribute("data-abzemo-search-style","");document.head.appendChild(style);}
 if(style.sheet) build(); else style.addEventListener("load",build,{once:true});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
window.ABZEMO_AI_SEARCH={supportedLanguages:SUPPORTED_LANGUAGES};
})();