name: UZMO Runtime Tests

on:
  push:
    paths:
      - "uzmo/runtime/**"
      - "uzmo/uzmo.js"
  pull_request:
    paths:
      - "uzmo/runtime/**"
      - "uzmo/uzmo.js"

jobs:
  runtime-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: uzmo/runtime
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm test
